# Generated by Django 2.2.1 on 2019-05-09 10:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255)),
                ('municipality', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postCode', models.CharField(max_length=16)),
                ('streetName', models.CharField(max_length=255)),
                ('houseNumber', models.CharField(max_length=16)),
                ('apartmentNumber', models.CharField(blank=True, max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=2048)),
                ('type', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('nrBedrooms', models.IntegerField()),
                ('nrBathrooms', models.IntegerField()),
                ('squareMeters', models.IntegerField()),
                ('constructionYear', models.IntegerField()),
                ('dateCreated', models.DateTimeField()),
                ('sold', models.BooleanField()),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='realEstate.Address')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=1024)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realEstate.Property')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAttribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realEstate.Attribute')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realEstate.Property')),
            ],
        ),
    ]
