# Generated by Django 2.2.1 on 2019-05-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='apartmentNumber',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='municipality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
