# Generated by Django 2.2.1 on 2019-05-10 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0003_auto_20190510_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.CharField(default='https://image.flaticon.com/icons/svg/149/149445.svg', max_length=1024),
        ),
    ]
