# Generated by Django 2.2.1 on 2019-05-10 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0004_auto_20190510_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyimage',
            name='image',
            field=models.CharField(max_length=1024),
        ),
    ]
