# Generated by Django 2.2.1 on 2019-05-14 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0005_auto_20190510_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='attibutes',
            field=models.ManyToManyField(to='realEstate.Attribute'),
        ),
        migrations.DeleteModel(
            name='PropertyAttribute',
        ),
    ]
