# Generated by Django 2.2.1 on 2019-05-14 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realEstate', '0006_auto_20190514_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='attibutes',
            new_name='attributes',
        ),
    ]
