# Generated by Django 2.2.1 on 2019-05-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=0, max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='profileImage',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
