# Generated by Django 2.2.1 on 2019-05-13 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190510_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentlyviewed',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
